version: "3.9"

services:
  postgres:
    image: postgres:16
    containar_name: twitter_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter_like
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresqldata
    networks:
      - twitter_net